apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: todo-api
spec:
  template:
    spec:
      containers:
      - env:
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: myenv
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PASSWORD
              name: myenv
        - name: DATABASE_SVC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_SVC_HOSTNAME
              name: myenv
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              key: DATABASE_USER
              name: myenv
